# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: "Home"
#    url: "#intro"
#    weight: 10
  - name: "Projetos"
    url: "#projects"
    weight: 20
  - name: "Time"
    url: "/#team"
    weight: 60
#  - name: "About"
#    url: "about"
#    weight: 50
  - name: "Seminários"
    url: "#seminars"
    weight: 30
#  - name: "Serviços"
#    url: "#contato"
#    weight: 50
  - name: "Contato"
    url: "#contact"
    weight: 40
  - name: "Estatísticas"
    url: "metrics/"
    weight: 90
  - name: "Conferências"
    identifier: conferences
    weight: 100
  - name: "FENS 2022"
    parent: conferences
    url: "https://open-neuroscience.com/FENS-2022/"
    weight: 90
  - name: "ERM2023"
    parent: conferences
    url: "https://open-neuroscience.com/ERM2023/"
    weight: 100
